### ISSUE TITLE
Support for Blade 2019 (i7 8750H, 2080MQ)

### ISSUE THREAD

**Issue by RoastedHobnai1** [tdakhran/razer-ctl#4]
Enumerate output:
`PS C:\Users\v_opo\Downloads> .\razer-cli.exe enumerate`
`RazerDevice { vid: 0x1532, pid: 0x023a, manufacturer: Razer, product: Razer Blade }`
`RazerDevice { vid: 0x1532, pid: 0x023a, manufacturer: Razer, product: Razer Blade }`
`RazerDevice { vid: 0x1532, pid: 0x023a, manufacturer: Razer, product: Razer Blade }`
`RazerDevice { vid: 0x1532, pid: 0x023a, manufacturer: Razer, product: Razer Blade }`
`RazerDevice { vid: 0x1532, pid: 0x023a, manufacturer: Razer, product: Razer Blade }`
`RazerDevice { vid: 0x1532, pid: 0x023a, manufacturer: Razer, product: Razer Blade }`
`RazerDevice { vid: 0x1532, pid: 0x023a, manufacturer: , product:  }`
`RazerDevice { vid: 0x1532, pid: 0x023a, manufacturer: Razer, product: Razer Blade }`

Info output:
`PS C:\Users\v_opo\Downloads> .\razer-cli.exe -p 0x023a info`
`Error: hidapi error: HidD_SetFeature: (0x00000001) Incorrect function.`

**Comment by tdakhran** [comment]
Thanks for reporting the issue @RoastedHobnai1. `Incorrect function` was fixed in #2 but not yet released. If you can build `HEAD` and try it, that would be helpful.

Otherwise you can wait for release, I'll do it after #8 functionality is merged.

**Comment by RoastedHobnai1** [comment]
Oh, didn't think that you're still working on the project!

Compiled and tested - something's still broken:
`PS C:\Users\Vladimir\Downloads> .\razer-cli.exe enumerate`
`RazerDevice { pid: 0x023a, path: \\?\HID#VID_1532&PID_023A&MI_01&Col05#7&3a2dd8e&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030} }`
`RazerDevice { pid: 0x023a, path: \\?\HID#VID_1532&PID_023A&MI_02#7&20346034&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} }`
`RazerDevice { pid: 0x023a, path: \\?\HID#VID_1532&PID_023A&MI_00#7&277a1b50&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\KBD }`
`RazerDevice { pid: 0x023a, path: \\?\HID#VID_1532&PID_023A&MI_01&Col01#7&3a2dd8e&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\KBD }`
`RazerDevice { pid: 0x023a, path: \\?\HID#VID_1532&PID_023A&MI_01&Col02#7&3a2dd8e&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030} }`
`RazerDevice { pid: 0x023a, path: \\?\HID#VID_1532&PID_023A&MI_01&Col03#7&3a2dd8e&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030} }`
`RazerDevice { pid: 0x023a, path: \\?\HID#VID_1532&PID_023A&MI_00&Col03#8&2658cb92&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} }`
`RazerDevice { pid: 0x023a, path: \\?\HID#VID_1532&PID_023A&MI_01&Col04#7&3a2dd8e&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030} }`
`PS C:\Users\Vladimir\Downloads> .\razer-cli.exe -p 0x023a info`
`Error: Failed to get performance mode and fan mode: Ok((Balanced, Auto)) Err(Command failed with unknown status: 01)`

Let me know if there's anything else I can provide to help!

**Comment by tdakhran** [comment]
@RoastedHobnai1  I pushed big change #14 , it might unblock `razer-cli` functionality for your laptop. The output of `razer-cli.exe manual --pid 0x023a info` and `razer-cli.exe enumerate` would be very helpful!

**Comment by RoastedHobnai1** [comment]
@tdakhran , thank you for the update!
Here you go:

```
PS C:\Users\Vladimir\Downloads> .\razer-cli.exe enumerate
Model: RZ09-02888
Supported: false
PID: [
    0x023a,
]
PS C:\Users\Vladimir\Downloads> .\razer-cli.exe manual --pid 0x023a info
Device: Descriptor { model_number_prefix: "Unknown", name: "Unknown", pid: 570, features: ["battery-care", "lid-logo", "lights-always-on", "kbd-backlight", "fan", "perf"] }
battery-care: Err(Command not supported)
lid-logo: Ok(Off)
lights-always-on: Ok(Disable)
kbd-backlight: Ok(0)
Fan: Auto
Performance: Ok((Balanced, Auto))
```
